/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as PhilosophyRouteImport } from './routes/philosophy'
import { Route as NotficationsRouteImport } from './routes/notfications'
import { Route as IndexcopyRouteImport } from './routes/index copy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BetaRouteImport } from './routes/beta'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogBIdRouteImport } from './routes/blog/$bId'

const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophyRoute = PhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotficationsRoute = NotficationsRouteImport.update({
  id: '/notfications',
  path: '/notfications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexcopyRoute = IndexcopyRouteImport.update({
  id: '/index copy',
  path: '/index copy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaRoute = BetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBIdRoute = BlogBIdRouteImport.update({
  id: '/blog/$bId',
  path: '/blog/$bId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRoute
  '/about': typeof AboutRoute
  '/beta': typeof BetaRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/index copy': typeof IndexcopyRoute
  '/notfications': typeof NotficationsRoute
  '/philosophy': typeof PhilosophyRoute
  '/roadmap': typeof RoadmapRoute
  '/blog/$bId': typeof BlogBIdRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRoute
  '/about': typeof AboutRoute
  '/beta': typeof BetaRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/index copy': typeof IndexcopyRoute
  '/notfications': typeof NotficationsRoute
  '/philosophy': typeof PhilosophyRoute
  '/roadmap': typeof RoadmapRoute
  '/blog/$bId': typeof BlogBIdRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRoute
  '/about': typeof AboutRoute
  '/beta': typeof BetaRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/index copy': typeof IndexcopyRoute
  '/notfications': typeof NotficationsRoute
  '/philosophy': typeof PhilosophyRoute
  '/roadmap': typeof RoadmapRoute
  '/blog/$bId': typeof BlogBIdRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/beta'
    | '/community'
    | '/contact'
    | '/index copy'
    | '/notfications'
    | '/philosophy'
    | '/roadmap'
    | '/blog/$bId'
    | '/blog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/about'
    | '/beta'
    | '/community'
    | '/contact'
    | '/index copy'
    | '/notfications'
    | '/philosophy'
    | '/roadmap'
    | '/blog/$bId'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/beta'
    | '/community'
    | '/contact'
    | '/index copy'
    | '/notfications'
    | '/philosophy'
    | '/roadmap'
    | '/blog/$bId'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRoute
  AboutRoute: typeof AboutRoute
  BetaRoute: typeof BetaRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  IndexcopyRoute: typeof IndexcopyRoute
  NotficationsRoute: typeof NotficationsRoute
  PhilosophyRoute: typeof PhilosophyRoute
  RoadmapRoute: typeof RoadmapRoute
  BlogBIdRoute: typeof BlogBIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophy': {
      id: '/philosophy'
      path: '/philosophy'
      fullPath: '/philosophy'
      preLoaderRoute: typeof PhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notfications': {
      id: '/notfications'
      path: '/notfications'
      fullPath: '/notfications'
      preLoaderRoute: typeof NotficationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index copy': {
      id: '/index copy'
      path: '/index copy'
      fullPath: '/index copy'
      preLoaderRoute: typeof IndexcopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta': {
      id: '/beta'
      path: '/beta'
      fullPath: '/beta'
      preLoaderRoute: typeof BetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$bId': {
      id: '/blog/$bId'
      path: '/blog/$bId'
      fullPath: '/blog/$bId'
      preLoaderRoute: typeof BlogBIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRoute,
  AboutRoute: AboutRoute,
  BetaRoute: BetaRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  IndexcopyRoute: IndexcopyRoute,
  NotficationsRoute: NotficationsRoute,
  PhilosophyRoute: PhilosophyRoute,
  RoadmapRoute: RoadmapRoute,
  BlogBIdRoute: BlogBIdRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
